ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS query TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS rating NUMERIC(3,1);
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS reviews INTEGER DEFAULT 0;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS tags TEXT[];